### ISSUE TITLE
Include FQCN of role in callback data

### ISSUE THREAD

**Issue by Ladas** [ansible/ansible-runner#1019]
We have FQCN of module for every task. We also need FQCN of role for every task (which role is the task part of). 

Should be extended around https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/display_callback/callback/awx_display.py#L424-L425 adding a new field for `<namespace>.<collection_name>` of the role.

Usecases:
1. Visibility to collections name if roles are used with `collections:` definition  (without this, the event data won't provide us if the role is part of collection or not)
2. Easier way to parse collection when users use FQCN to include the role

**Comment by Ladas** [comment]
A follow up question: what can we do to also have FQCN for plugins and playbooks and how to expose that to Controller.

**Comment by sivel** [comment]
Core does already track the collection that the role is part of, in `task._role._role_collection`.  I've been thinking about this, and for actually using the collection loader, `task._role._role_name` would be a correctly formatted role name.  Outside of collection use the role name is just whatever the user supplied, so it can come in numerous forms.

Just tracking the collection would be easy since it's already there.  I don't really love poking at too many internal attrs, so just an FYI that `task._role.get_name()` will return the full FQCN directly.

With that in mind, I wonder if just using `task._role.get_name()` for `task_role` is just the best thing to do.  Outside of a collection use it just gives you the standalone name, or in a collection context, gives you the FQCN.

**Comment by Akasurde** [comment]
@AlanCoding Does PR #1021 resolve this issue?

**Comment by Ladas** [comment]
@Akasurde yes, this has been solved.

**Comment by Akasurde** [comment]
@Ladas Thanks for the confirmation.
