### ISSUE TITLE
Examples on how to use event_handler and status_handler

### ISSUE THREAD

**Issue by Kamatam** [ansible/ansible-runner#1078]
I am trying with following python code to run the playbook using ansible_runner and ansible_runner_http but not able to find how to use event_handler and status_handler. Please suggest some example on this

import ansible_runner
from ansible_runner_http.events import event_handler
r = ansible_runner.run(private_data_dir='/tmp/ansible/,
 playbook='test1.yml',
 event_handler=None)

**Comment by Akasurde** [comment]
@Kamatam Thanks for reporting this issue. Could you please give us the use case of `event_handler` and `status_handler`?

**Comment by Akasurde** [comment]
Simplest example - 

```python
def my_event_handler(data):
    # Do something useful here
    print(data)

r = ansible_runner.run(
    host_pattern='all',
    module='ping',
    event_handler=my_event_handler,
    inventory='virtualbox.yml')
```

**Comment by Kamatam** [comment]
@Akasurde thank you for the details. My use case is to send the data to http(s) rest endpoint for specific events only instead for every event. For example, send playbook task result's events. Currently http event handler (with runner_http_url) triggers for every event.

**Comment by matburt** [comment]
What you are asking for might be a little on the complex side... what @Akasurde showed you is a basic example of how to pass the event handler in... filtering events and sending them along is a little bit more involved. The `data` parameter is going to contain a python dictionary and the data structure will look like this: https://ansible-runner.readthedocs.io/en/stable/intro/#artifactevents

What you want to do is filter on the event type you are looking for ... we document this a little bit in the AWX architecture documentation: https://github.com/ansible/awx/blob/devel/docs/job_events.md#job-event-relationships

Which makes use of Runner behind the scenes.

You can modify the existing http plugin to do what you want and use yours instead of the http plugin.
