### ISSUE TITLE
how can i use it in java

### ISSUE THREAD

**Issue by zzz-Uzi** [ansible/ansible-runner#1169]
how can i use it in java.

**Comment by Shrews** [comment]
This question is very generic and I'm not sure what you are asking. Making a call to `ansible-runner` in Java is similar to making a call to any other external program, and is outside the scope of what we support.

If you have a question more specific to the usage of `ansible-runner` outside of the Java context, feel free to expand on that. Otherwise, we'll close this issue for you after some time.

**Comment by zzz-Uzi** [comment]
I have a module that calls Ansible to manage servers in bulk, but I don't find any dependencies on the Internet, so I don't know how to integrate Ansible into my Java code

**Comment by Shrews** [comment]
`ansible-runner` itself requires only Python 3.8 or higher.

`ansible`, which is called from `ansible-runner`, has its own list of requirements for the control node and the managed nodes, outlined in its installation docs: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html

If you use collections with Ansible, each of those has their own list of requirements and you'll need to refer to the collection documentation for those requirements.

Since this isn't directly an issue with `ansible-runner`, I'm going to close this issue now.
