### ISSUE TITLE
Ansbile Runner callback for stdout specified: awx_display Error

### ISSUE THREAD

**Issue by dogactopay** [ansible/ansible-runner#1190]
I am developing an agent that includes ansible-runner, while I am running any playbook it is normal.

However **_when I compile it using pyinstaller_**, I am getting the below error while executing the playbook.

`ansible_runner.run(playbook="win_restart_service.json")`

### ERROR! Invalid callback for stdout specified: awx_display

**Comment by Shrews** [comment]
Using `pyinstaller` is not one of the recommended/supported installation methods (see https://ansible-runner.readthedocs.io/en/stable/install/). I've never used that utility and not sure how to help you with that, but if you figure out what the issue is, we'd be happy to consider a PR to add the necessary support. You can find the relevant portion of code dealing with the callback [here in the source](https://github.com/ansible/ansible-runner/blob/a4a981d67c7e4f4209381c6fedbb7f1fa4942098/ansible_runner/config/_base.py#L264-L293).
