### ISSUE TITLE
Allow awx_display.py to support a configuration for using a time zone instead of UTC

### ISSUE THREAD

**Issue by gqfcode** [ansible/ansible-runner#1236]
def current_time():
    return datetime.datetime.utcnow()

**Comment by sivel** [comment]
Due to the reliance that we have on this TZ being UTC, we've decided not to allow this to be configurable.  However, during reviewing the code, we realized that although the ISO8601 datetime strings we were emitting were intended to be UTC, we were not including the timezone on them, and have submitted a pull request to address this issue.

Any need to represent these datetime strings in another timezone can be done, by parsing the string into a datetime object, and converting the timezone.  In python:

```pycon
>>> import datetime

>>> created = datetime.datetime.fromisoformat(event['created'])

>>> local_created = created.astimezone(datetime.datetime.now().astimezone().tzinfo)

>>> local_created
datetime.datetime(2023, 4, 25, 15, 26, 15, 210771, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'CDT'))
```
