### ISSUE TITLE
ansible-runner doesn't support ANSIBLE_ENABLE_TASK_DEBUGGER

### ISSUE THREAD

**Issue by fao89** [ansible/ansible-runner#1327]
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_debugger.html#enabling-the-debugger-in-configuration-or-an-environment-variable
When I set `ANSIBLE_ENABLE_TASK_DEBUGGER=true`  and execute my playbook with the `ansible-runner`:
```
ansible-runner run /runner -p osp.edpm.nova
```
it gets stuck, and it isn't possible to use the debugger
![image](https://github.com/ansible/ansible-runner/assets/17153022/b74efe23-6efb-495d-bd89-7776f5a30735)

If I run the same playbook with `ansible-playbook`
```
ansible-playbook -i inventory/hosts osp.edpm.nova
```
I can see the `(debug)>` prompt 
![image](https://github.com/ansible/ansible-runner/assets/17153022/b44b4aeb-8845-4781-909a-55c67572af1d)

**Comment by sivel** [comment]
I'm curious why you want to have the task debugger enabled when running playbooks through runner.

**Comment by fao89** [comment]
@sivel to be honest, I never used the debugger. I bumped into this issue because this var was set to true in a sample and I didn't know why my playbook was getting stuck on error. I could only see it once I ran with `ansible-playbook`.

**Comment by Shrews** [comment]
I'm going to close this because using the debugger under runner is not a scenario that is ever going to work because of the need for manual interaction with the debugger itself. Runner does not (nor will it ever) have the ability to process manual interaction with Ansible except for very limited ability to recognize and handle password prompts. If you need to use the debugger, you'll have to run `ansible-playbook` directly.
