### ISSUE TITLE
MAX_EVENT_RES environment variable truncating event['res'] return data

### ISSUE THREAD

**Issue by rtproven** [ansible/ansible-runner#326]
Hello,

I was wondering if someone could explain the need for the environment variable **MAX_EVENT_RES** environment variable found in the _display_callback/events.py_ module and possibly offer any guidance to setting it beyond the default value of 700,000 bytes?

Thanks,
Roland Provencher

**Comment by matburt** [comment]
This setting is there to protect the event consumer (Runner, or whatever is sitting on the other side of the event callback if you're using that aspect of the Runner module interface) from an out-of-control module or a user mistake. This kind of thing[ has been in the AWX/Tower product for years](https://github.com/ansible/awx/commit/a61e729ebbc27a85e492010f3571cb659c8f8762) and I've never seen anyone need this value raised.

Remember that this represents the maximum size of data that is allowed to be returned as part of an event/task from within Ansible, it has nothing to do with the input or execution of that task.

I'll give you an example of *why* this is useful by telling you the story of why it was implemented in the first place. One day a user accidentally sent a 3GB tarball through a templated variable as part of a task that reproduced the value of the variable in the event data and it segfaulted by running the collector process out of memory. The act of running the system out of memory also caused some other catastrophic behavior because it was running as part of a production AWX/Tower system.

It's there as a knob in case you need it, most people don't and it's there to keep you or a user from accidentally shooting themself in the foot.

**Comment by matburt** [comment]
I honestly picked that value because it was about 20% higher than the largest useful value I have ever seen come out of the event data structure.

**Comment by rtproven** [comment]
Hi Matthew,
Thanks for the information.  We have a customer with an ~400KB config file and the Ansible module being used to retrieve the config duplicates the overall data by returning it as a raw buffer as well as an array of lines.  The combination of the 2 puts the event results over the 700000 limit.  The customer was running fine then all of a sudden was not receiving any results.  After some poking around in the runner code, adjusting the MAX_EVENT_RES environment variable got them going again.  Is there any indication in the results or status returned back from Runner that this threshold has been crossed?

Thanks again,
Roland Provencher
