### ISSUE TITLE
Pin Docker Image Versions for ansible/ansible-runner

### ISSUE THREAD

**Issue by drenze** [ansible/ansible-runner#489]
I have a requirement in our environment to use ansible for deployment in our CI/CD environment, however I also have a requirement to pin versions. I.e., I'm unable to use a `latest` tag in our environment, in order to ensure consistency in deployments and to test for breaking changes (for example, if `latest` marks a major release). It would not surprise me if I'm not the only one with such requirements.

To remediate this issue, I would request that as new images are built and deployed to Docker Hub, they are tagged with version, as well as with `latest`, for those who choose to use it. I.e., the current version, as of this request would be `ansible/ansible-runner:2.9.9`. The alternative is build and manage our own images, which is cumbersome.

**Comment by AlanCoding** [comment]
@kdelee I think part of the confusion here is that `make image` takes `IMAGE_NAME`, assuming this is in the form of `image-name:tag`. I find this difficult to manage, but I don't want to change the meaning of Makefile variables and break infrastructure because of it.

In #520 I'm moving in the direction of a `GIT_BRANCH` Makefile variable, then with some string processing that gets added as the `:tag` part.

We also have a `VERSION` variable, but even in my PR I'm not attempting to tag with this. I see the need to tag with the runner version, but _only as a part of release_.

I also don't like the idea of tagging with ansible-runner version and _also_ having Ansible in there. Both versions are relevant to the core operation of playbooks. The proposal I am trending towards (which has lots of problems) is to cut "primordial" images without Ansible, tagged with the runner version.

**Comment by shanemcd** [comment]
We have effectively solved this using our new tagging pattern, which we will use from 2.0+ https://quay.io/repository/ansible/ansible-runner?tab=tags
