### ISSUE TITLE
Ansible runner & 'env/' directory

### ISSUE THREAD

**Issue by dcasasok** [ansible/ansible-runner#493]
Hi, i'm trying to understand how env/ directory works in ansible runner...
First all, i'm using runner as a python module. So i run ansible_runner.interface.run_async() with parameters :
extravars: dictionary parameter
settings: dictionary parameter
envvars: dictionary parameter
When i execute my script for first time it creates  the env/ path in my local directory, where each file contain all parameters data.
Altrought i execute again, those files are still existing and not overwriting.
If i run ansible runner script with debug -vvvv, i saw: 
		extra_vars: ('@/var/ansible-runner/project/XXX/env/extravars' , '{ "my_extra_vars" : nnnnnn }' )  
		where my dict {"my_extra_vars": nnnn} is a representation.
Which parameters ansible runner interface must to use?
What are the usefulness of env/ directory?

**Comment by AlanCoding** [comment]
If you are using it as a python interface and pass `settings` (for example), then it lays down files YAML vars for what you passed in `env/settings`. This is a convenience thing, so that you don't have to write them to a file in order to use ansible-runner.

https://github.com/ansible/ansible-runner/blob/743793be10487468ea36d323dc054205ddeae2de/ansible_runner/utils.py#L199-L201

Speaking anecdotally, it does not clean up these setting files at the end of the run, and I agree it should. I have gotten an error when I provided non-empty settings but the file existed. Sounds like you got a different result, so I would like to know more specifically what your code looks like when it uses the ansible-runner python interface.

**Comment by rajasaur** [comment]
I encountered a similar result and did not expect the parameters to be persisted especially as these are passed at runtime. Like a standalone ansible-playbook, I was expecting the process to just receive the values, run the playbook and not persist any values. 

In my case, I ran it with extravars, which created a env/extravars and stored the values there. I ran it a second time *without* passing extravars and expected an error from Ansible since there was no value passed during the run, but it was successful as it used the value from the previous run. That wasnt the behaviour with ansible-playbook.

**Comment by matburt** [comment]
I agree, I'd like Runner to be able to clean these up.

**Comment by AlanCoding** [comment]
Behavior described in duplicate issue:

```
(env) [djuran@localhost ~]$ env/bin/python3 test.py
Traceback (most recent call last):
File "test.py", line 8, in
settings={})
File "/home/djuran/env/lib64/python3.6/site-packages/ansible_runner/interface.py", line 177, in run
r = init_runner(**kwargs)
File "/home/djuran/env/lib64/python3.6/site-packages/ansible_runner/interface.py", line 64, in init_runner
rc = RunnerConfig(**kwargs)
TypeError: init() got an unexpected keyword argument 'settings'
```

This is what I have seen as well, on the 2nd run or any other subsequent runs. Several tests are now working around this behavior.

**Comment by lleontop** [comment]
Hi, I also stumbled across this issue while passing envvars parameters to ansible-runner as a python module interface. Is there any update on this? I would expect the runner should always respect whatever envvars/extravars are/if passed from the module call even if the `env/` directory exists. 

Edit: With regards to envvars I think the order of updating `self.env` in https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/config/_base.py#L204 would make sense to change and give different priority. Load the `env/envvars` file first and then update with whatever is passed as envvars parameter. I could probably procced with a PR if you agree!

Thanks!

**Comment by FloLaco** [comment]
This PR should fix the issue about `settings` : https://github.com/ansible/ansible-runner/pull/811

The issue about precedence between dict argment and file is here : 

https://github.com/ansible/ansible-runner/blob/da332d69141b8318bd3560eec2316fdbed73d21c/ansible_runner/config/_base.py#L217 

and here : https://github.com/ansible/ansible-runner/blob/da332d69141b8318bd3560eec2316fdbed73d21c/ansible_runner/config/_base.py#L222

You should swap this two block of code.
First we import the file and update the env.
Then we update the env with the envvars provided by argument in `interface`

**Comment by Smixi** [comment]
I ran into this issue recently, we use a service to deploy stuff through ansible, and changing data that we pass to Ansible python interface, the env/extravars is merged. But even merging is not OK, because we use the same project with different inventory and env variable, leading to deployment having too much extravars from old execution, not only bad values, too much also.

**Comment by AlanCoding** [comment]
An option to not write files in the `env/` directory was added in https://github.com/ansible/ansible-runner/pull/1000

Perhaps that can be said to resolve this issue?

**Comment by Smixi** [comment]
@AlanCoding yep it will do for me :). It just felt weird that is was taking up both config (extravars in folder and through python interface), but in my use case I can never it and it will work perfectly. Thanks :).
