### ISSUE TITLE
No module named psutil

### ISSUE THREAD

**Issue by cdvv7788** [ansible/ansible-runner#54]
When running the demo python code, I am getting:
![image](https://user-images.githubusercontent.com/5531776/41295389-1d34c67e-6e20-11e8-90e5-d16f70271805.png)

I am running it using the following environment:
![image](https://user-images.githubusercontent.com/5531776/41295456-408f0364-6e20-11e8-90da-48d2965b671d.png)

As it can be seen in the attached image, I do have psutil. Ansible-runner is updated.

**Comment by cdvv7788** [comment]
The issue was happening because I didn't have ansible installed in my venv. Not familiar enough to know if that is the case, but shouldn't ansible be a dependency on setup?
Also, the error does not give a hint about the cause.

**Comment by matburt** [comment]
This has a bit to do with the Runner callback plugin/interface needing psutil in order to handle the processes spawned by Ansible itself. We *do* have psutil installed alongside Runner but if Ansible itself exists *outside* of your venv then it obviously won't have access to it.

Not usually a problem for standard packaging but it is in this scenario. I'm open to suggestions on this one.

**Comment by cdvv7788** [comment]
Well, I didn't have ansible installed at all. At least for the python interface, it may be natural for ansible to be a dependency for this package. After all, this package does depend on ansible to be able to work.
Other than that, I don't know what else to suggest at this time.

**Comment by matburt** [comment]
I've thought about having ansible as a dependency but it takes away some of the flexibility of the tool itself.

I want folks to be able to bring any supported ansible version that they want, and be able to pull it from any source. Even something as flexible as having runner be pip installed in python 3 and ansible installed from distro packaging into python 2.

Adding a hard dependency on Ansible itself makes that very difficult.

**Comment by cdvv7788** [comment]
Well, that makes a lot of sense. Is there a way to detect that ansible is missing? I mean, that may be obvious once you find out, but if for some reason the tool is unable to find ansible, all we have is a message saying that "no module named psutil".

**Comment by matburt** [comment]
Yep, you are right. We could/should add a pre-launch check eithere here:

https://github.com/ansible/ansible-runner/blob/master/ansible_runner/interface.py#L30

or, and this is probably better, as part of these:

https://github.com/ansible/ansible-runner/blob/master/ansible_runner/runner_config.py#L90

If we can't find ansible in the path we could immediately issue an error and drop out. I'm trying to think of a scenario where we might want to skip that check (and add a bypass) the only scenario I can think of might be if this file is populated: https://github.com/ansible/ansible-runner/blob/master/ansible_runner/runner_config.py#L191-L194

This is currently a shortcut way to bypass the `Runner` command-line generation process. It's undocumented and is vestigial from the way the old Tower/AWX system works where the task engine was responsible for generating the command line.  This may go away in the future (hence why it's undocumented) but for the moment it's still there. The reason I say all of that is because it's feasible that this `args` file could call something that's outside of the path (and in another virtualenv, for example).  This is not how Tower/AWX works right now so I wouldn't worry too much about it, nor would I worry about a bypass necessarily unless we can come up with another reason that Ansible wouldn't be in the path but would be executable later (setting `PATH` as part of `envvars` perhaps?)

**Comment by carbonin** [comment]
Sorry to attach to this old issue, but I'm having this exact problem with most distributions of `ansible-runner` on Fedora.

I was able to get one to work (installed from the fedora repos), but I'm stuck with this same problem if I install via `pip`, or using the ansible releases rpm.

Specifically I find it strange that I can run `ansible-playbook` for the demo playbook, but not `ansible-runner`.

```
17:59:16:~/Source/ansible-runner (master)$ ansible-runner --playbook test.yml run demo
ERROR! Unexpected Exception, this is probably a bug: No module named 'psutil'
to see the full traceback, use -vvv
17:59:31:~/Source/ansible-runner (master)$ ansible-playbook --inventory localhost, -e ansible_connection=local demo/project/test.yml 

PLAY [all] ***********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Test!"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

I know there must be some step I'm missing, but I can't figure out how to get psutil installed properly.

Currently I removed all the ansible-runner rpms and tried to install using `pip3 install ansible-runner --user`, but am having no luck.

If this is something simple can we get this added to the documentation?

**Comment by carbonin** [comment]
So for what it's worth, to fix this I had to have ansible, ansible-runner, and psutil all installed via `pip3` rather than installing ansible or ansible-runner using `dnf`

**Comment by matburt** [comment]
They definitely all have to be installed at the same level of environment, unfortunately. I'd *really* like to have the psutil requirement removed entirely as I'm not sure it's strictly needed anymore.

**Comment by carbonin** [comment]
I think my issue was that I moved from one rpm-based solution to another and things broke.

ansible-runner from the Fedora `updates` repo works with ansible from the same location, but ansible-runner installed from https://releases.ansible.com/ansible-runner/rpm/epel-7-x86_64/ broke with this issue.

(I moved because 1.3 isn't available in `updates`)

**Comment by superfenv** [comment]
I have installed ansible and ansible_runner on the centos 7 system. When I execute it, I get an error: ERROR! Unexpected Exception, this is probably a bug: No module named psutil. Execution content r = ansible_runner.run (private_data_dir = '/ tmp / ansible_demo', module = "ping", host_pattern = "*", forks = 10)
print ("{}: {}". format (r.status, r.rc))

**Comment by uni1421** [comment]
我在Centos7上已经安装了ansible和ansible_runner、psutil 提示**ERROR! Unexpected Exception, this is probably a bug: No module named psutil**
![image](https://user-images.githubusercontent.com/37495490/109773582-558a3380-7c3a-11eb-9784-7373734db2cb.png)
