### ISSUE TITLE
Possibility to provide total_lines in emitted events?

### ISSUE THREAD

**Issue by SirUli** [ansible/ansible-runner#540]
First of all, thanks for your amazing project :) 

Then a little question: in the emitted events from runner you are providing the start_line and end_line. I'm missing something like the "total_lines" so that we could e.g. calculate a percentage on how far a playbook has progressed. Is there any way this could be added (besides opening the playbook and reading the number of lines outside of runner of course) to the events?

Thanks in advance!

Best Regards, Uli

**Comment by AlanCoding** [comment]
The callback for `event_handler` is called when the event is produced and it is _very important_ that this happens before the playbook is finished, particularly for long-running playbooks. We cannot know how many lines a playbook will produce in advance.

However, we do have a `status_handler`, which will indicate the finished status at a point. It doesn't give a metric like total_lines, but this could be relatively easily put together by creating your own python class with both event & status handler, and then saving the `end_line` to a variable like `self.total_lines` and then reading that from the status handler.

Coincidentally, I might be doing this exact thing in https://github.com/ansible/awx/pull/8323 (but have not yet).

Hope this answers the question, I can't imagine adding this directly, because it's very disruptive to change the callback call pattern.

**Comment by SirUli** [comment]
Thanks for the explanation - i was hoping that i overlooked something but this totally makes sense then. Thanks again!
