### ISSUE TITLE
[execution-environments] Need a way for ansible-runner worker to delete the private data dir

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-runner#621]
Consider the example:

```
ansible-runner transmit demo -p test.yml > /tmp/output
ansible-runner worker --private-data-dir alan < /tmp/output > /tmp/output2
ansible-runner process demo < /tmp/output2
```

After this finishes, inspect `ls alan`. You find that the worker's private data dir still exists after it has completed.

This will not be acceptable with a separate control plane & execution plane. When a job ran as a part of AWX / Tower finishes, the default settings need to be that the data files from the job are deleted from all nodes involved. It is expected that this directory will contain secrets.

**Comment by shanemcd** [comment]
Not a blocker for 4.0 because:

- When jobs are executed directly on the control plane, AWX itself handles cleaning up the private data dir after the job completes.
- When jobs run in a remote pod via Container Groups, any disk space used during the duration of the run is freed up when the container finishes running.

**Comment by AlanCoding** [comment]
this was implemented, and I can't toggle labels so I will just close it
