### ISSUE TITLE
home directory .ansible-runner

### ISSUE THREAD

**Issue by matburt** [ansible/ansible-runner#699]
Right now we make use of `~/.ansible-runner` : https://github.com/ansible/ansible-runner/blob/a151df7fc43c1ebfe9e72c1193603a3d3e50b046/ansible_runner/config/_base.py#L91

I think we might want to shift this to `/tmp/.ansible-runner`

and then add an `@property` to https://github.com/ansible/ansible-runner/blob/a151df7fc43c1ebfe9e72c1193603a3d3e50b046/ansible_runner/runner.py#L26 that points to the location of the private data dir.

**Comment by abadger** [comment]
Hey, I was going through some security issues with ansible-navigator today and this change to runner came up.  What is the rationale for using /tmp/ instead of ~/.ansible-runner?  For security purposes, it is always better to not use /tmp/.  I believe David Wheeler once even recommended that /tmp/ should only be used when you intentionally want to share files.

(I can wax on for pages with reasons not to use /tmp/ but if I know the reason it was seen as desirable I might be able to propose an alternative instead).

**Comment by matburt** [comment]
My concern when running in container environments if you *might* not have something that looks like a home directory. This also lets us just use a vanilla call to https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp and it'll find the right place. Existing runner tooling usage has to satisfy the private data dir ahead of time already. This is just a fallback... for dev tools it should end up being adjacent to the project directory.

**Comment by abadger** [comment]
Cool.  I would suggest, at minimum, using mkdtemp, then, rather than using
`gettempdir() + ".ansible_runner" `.  mkdtemp is coded to be as secure as
the operating system allows. gettempdir () + a static name is trivially
exploitable.

Even better would be try to use a home dir and fallback to mkdtemp if that
fails but as you say, just coding to use mkdtemp is simpler to write... You
just have to be wary of any leakage of the directory name or race
conditions that you might introduce in other code as a result of using a
subdirectory of temp.

**Comment by matburt** [comment]
Looks like you did it yourself https://github.com/ansible/ansible-runner/pull/742 ?

**Comment by abadger** [comment]
Yes.  I wanted to look for other tempdir problems as well.
