### ISSUE TITLE
Allow archives as an alternative data-dir input

### ISSUE THREAD

**Issue by matburt** [ansible/ansible-runner#9]

**Comment by cdvv7788** [comment]
@matburt Can you elaborate please? What do you mean by "archives"? A compressed file with the required structure? In that case, what would the supported formats?

**Comment by matburt** [comment]
@cdvv7788 that's right, probably anything supported by these:

https://docs.python.org/3/library/archiving.html

**Comment by AlanCoding** [comment]
@jbradberry with the receptor integration, are private data dirs going to be put into tar files before being sent? If that's purely internal, then won't solve this issue, but maybe the logic could be reused.

**Comment by jbradberry** [comment]
Yes, that's right.

**Comment by matburt** [comment]
This is ultimately where I had hoped to get...

**Comment by AlanCoding** [comment]
Proposal to allow harmony with #505:

A new command `ansible-runner bundle`.

This command will take _all_ the options as `ansible-runner run`. It will write them to a new file as JSON, location and naming to-be-decided.

Then the private_data_dir, including this new file, will be put into a zip file at the specified output location.

Ideally, if any paths are given to places outside of the private_data_dir, then the `ansible-runner bundle` command will throw an error, because this will not work on a remote machine. Everything needs to be inside the private_data_dir for portability.

The zip file can be passed to `ansible-runner run <zip_file.zip>`, but if any other options are specified, it will error. The options are contained in the zipfile, and they cannot be overridden for the remote run.

**Comment by jbradberry** [comment]
@matburt how is this intended to work?  Are we assuming that the tarball/zipfile will just be unpacked into an anonymous tempdir and that is treated as the private_data_dir?

**Comment by shanemcd** [comment]
I do think this is basically done with `ansible-runner transmit` / `ansible-runner worker` / `ansible-runner process`. Shall we close this?
