### ISSUE TITLE
Add support for custom stats

### ISSUE THREAD

**Issue by NoSuchCommand** [ansible/ansible-runner#949]
The `Runner` object does not seem to report the custom stats set using the `set_stats` builtin Ansible module.

I would expect to find them in `Runner.stats` in a `custom_stats` key, or in its own `Runner.custom_stats` property.

**Comment by Shrews** [comment]
Is this a bug report or a feature request?

We don't currently store any statistics other than the high-level data reported at the end of the `ansible-playbook` run, so it's expected that you would not see any data from `set_stats`. That being said, I don't think it would be impossible to do this, but I'm not sure it's something we want to do. It would require deeper processing of the event data returned from the callbacks, and would open the door for requests for data from lots of other individual module result data. Since you do have the event data in the `artifacts` directory, you could process this data yourself, though.

I'm going to close this issue since we don't plan to implement this at this time. Thanks for your report.
